- name: check version
  shell: "vers={{ wazo_distribution }}; echo ${vers##*-} $(cat /usr/share/wazo/WAZO-VERSION); test ${vers##*-} = $(cat /usr/share/wazo/WAZO-VERSION)"
  when: wazo_debian_repo == "archive"

- name: Check that wazo-auth is listed in Consul services
  shell: "consul catalog services|grep wazo-auth"
  register: result
  until: result.rc == 0
  retries: 6
  delay: 10

- name: Get token
  uri:
    url: "https://{{ engine_api_host}}:{{ engine_api_port}}{{ engine_auth_path }}/token"
    method: POST
    validate_certs: no
    body_format: json
    force_basic_auth: yes
    user: "{{ api_client_name }}"
    password: "{{ api_client_password }}"
    body:
      expiration: 3600
    return_content: yes
  register: token_data

- name: debug token data
  debug:
    var: token_data

- name: Get users
  uri:
    url: "https://{{ engine_api_host}}:{{ engine_api_port}}{{ engine_confd_path }}/users"
    headers:
      X-Auth-Token: "{{ token_data.json.data.token }}"
    method: GET
    validate_certs: no
    return_content: yes
  register: users_data

- name: debug users data
  debug:
    var: users_data

- block:
    - name: Get the home page
      uri:
        url: "https://{{ groups['uc-ui'][0] }}/"
        validate_certs: false
      register: home_page

    - name: debug home_page data
      debug:
        var: home_page

    - name: verify redirect url
      assert:
        that:
          - home_page.url == "https://{{ groups['uc-ui'][0] }}/login/"
          - home_page.redirected

  when: groups['uc-ui'] is defined
