---
- name: Install APT python bindings and GPG
  apt:
    name:
      - python-apt
      - gpg
    state: present

- name: Add Wazo distribution key
  apt_key:
    url: https://deb.b5.pm/debian/sparrow.key
    id: E61CAE8DC859F6CBCB74AFBA7C2FA32DA9C16D93
    state: present

- name: Gather packages facts
  package_facts:
    manager: apt

- name: Add bootstrap Wazo repository
  apt_repository:
    repo: deb http://deb.b5.pm/{{ 'debian' if wazo_debian_repo == 'main' else wazo_debian_repo }} {{ wazo_distribution }} main
    state: present
    filename: wazo-install
    update_cache: yes
  when: '"wazo-dist" not in ansible_facts.packages'

- name: Install wazo-dist
  apt:
    name: wazo-dist
    state: latest

- name: Add persistent Wazo repository
  command: wazo-dist --{{ wazo_debian_repo }}-repo {{ wazo_distribution }}

- name: Remove bootstrap Wazo repository
  apt_repository:
    repo: deb http://deb.b5.pm/{{ 'debian' if wazo_debian_repo == 'main' else wazo_debian_repo }} {{ wazo_distribution }} main
    state: absent
    filename: wazo-install
    update_cache: yes
  when: '"wazo-dist" not in ansible_facts.packages'
