---
- name: Install APT python bindings and GPG
  apt:
    name:
      - python-apt
      - gpg
    state: present

- name: Add Wazo distribution key
  apt_key:
    url: https://deb.b5.pm/debian/sparrow.key
    id: BED5D81E6CAC5B901B4695CDA42C41005E51DF17
    state: present

- name: Gather packages facts
  package_facts:
    manager: apt

- name: Add bootstrap Wazo repository
  apt_repository:
    repo: deb http://deb.b5.pm/{{ 'debian' if wazo_debian_repo == 'main' else wazo_debian_repo }} {{ wazo_distribution }} main
    state: present
    filename: wazo-install
    update_cache: yes
  when: '"wazo-dist" not in ansible_facts.packages'

- name: Install wazo-dist
  apt:
    name: wazo-dist
    state: present

- name: Add persistent Wazo repository # noqa 301
  command: wazo-dist --{{ wazo_debian_repo }}-repo {{ wazo_distribution }}

- name: Remove bootstrap Wazo repository
  apt_repository:
    repo: deb http://deb.b5.pm/{{ 'debian' if wazo_debian_repo == 'main' else wazo_debian_repo }} {{ wazo_distribution }} main
    state: absent
    filename: wazo-install
    update_cache: yes
  when: '"wazo-dist" not in ansible_facts.packages'

- name: Add extra repository
  apt_repository:
    repo: "{{ wazo_extra_repository }}"
    state: present
    filename: "{{ wazo_extra_repository_filename }}"
    update_cache: yes
  when: wazo_extra_repository is defined
