---
- hosts: all
  become: yes
  roles:
    - role: preflight-checks

- hosts:
    - all
  become: yes
  roles:
    - role: debian-upgrade-first

- hosts:
    - redis
  become: yes
  roles:
    - role: wazo-redis

- hosts:
    - sbc
  become: yes
  roles:
    - role: wazo-c4-sbc
