---
- name: Install Wazo repo package source
  include_role:
    name: debian-repo-wazo

- name: Install the kamailio packages
  apt:
    name:
      - kamailio
      - kamailio-json-modules
      - kamailio-utils-modules
      - kamailio-extra-modules
      - kamailio-redis-modules
      - kamailio-xml-modules
    state: present
